DELETE FROM stockcurrent;
DELETE FROM stockdiary;
DELETE FROM stocklevel;
DELETE FROM products_bundle;
DELETE FROM uom;
DELETE FROM ticketlines;
DELETE FROM products_cat;
DELETE FROM products;
DELETE FROM tickets;
DELETE FROM payments;
DELETE FROM taxlines;
DELETE FROM receipts;
DELETE FROM stockcurrent;
DELETE FROM stockdiary;
DELETE FROM stocklevel;
DELETE FROM closedcash;
DELETE FROM csvimport;
DELETE FROM draweropened;
DELETE FROM lineremoved;
DELETE FROM leaves;
DELETE FROM breaks;
DELETE FROM shift_breaks;
DELETE FROM shifts;
DELETE FROM suppliers;
DELETE FROM taxsuppcategories;
DELETE FROM vouchers;

DELETE FROM pickup_number;
DELETE FROM ticketsnum;
DELETE FROM ticketsnum_payment;
DELETE FROM ticketsnum_refund;

INSERT INTO pickup_number (ID) VALUES(1);
INSERT INTO ticketsnum (ID) VALUES(1);
INSERT INTO ticketsnum_payment (ID) VALUES(1);
INSERT INTO ticketsnum_refund (ID) VALUES(1);

UPDATE smartpos.pickup_number SET ID = 1;
UPDATE smartpos.ticketsnum SET ID = 1;
UPDATE smartpos.ticketsnum_payment SET ID = 1;
UPDATE smartpos.ticketsnum_refund SET ID = 1;