-- Create PAYMENT_CATEGORIES table
CREATE TABLE PAYMENT_CATEGORIES (
    ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    IS_GLOBAL BIT DEFAULT 0,
    PRIMARY KEY (ID)
);

-- Insert default categories
INSERT INTO PAYMENT_CATEGORIES (ID, NAME) VALUES ('001', 'General');
INSERT INTO PAYMENT_CATEGORIES (ID, NAME) VALUES ('002', 'Office Supplies');
INSERT INTO PAYMENT_CATEGORIES (ID, NAME) VALUES ('003', 'Services');
INSERT INTO PAYMENT_CATEGORIES (ID, NAME) VALUES ('004', 'Wages');
INSERT INTO PAYMENT_CATEGORIES (ID, NAME) VALUES ('005', 'Other');

-- Add CATEGORY column to PAYMENTS table
ALTER TABLE PAYMENTS ADD COLUMN CATEGORY VARCHAR(255);
