package com.openbravo.pos.admin;

import com.openbravo.basic.BasicException;
import com.openbravo.data.loader.*;
import com.openbravo.pos.forms.AppConfig;
import java.io.File;
import java.util.*;

public class GrantAllPermissions {

    public static void main(String[] args) {
        try {
            System.out.println("Initializing GrantAllPermissions...");
            File configFile = new File("soltec.properties");
            AppConfig config = new AppConfig(configFile);
            config.load();
            
            String driver = config.getProperty("db.driver");
            String url = config.getProperty("db.URL");
            String user = config.getProperty("db.user");
            String password = config.getProperty("db.password");
            
            if (password != null && password.startsWith("crypt:")) {
                com.openbravo.pos.util.AltEncrypter cypher = new com.openbravo.pos.util.AltEncrypter("cypherkey" + user);
                password = cypher.decrypt(password.substring(6));
            }

            Class.forName(driver);
            Session session = new Session(url, user, password);
            
            // Construct the Permissions XML with comments and structure
            StringBuilder xml = new StringBuilder();
            xml.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
            xml.append("<!--\n");
            xml.append("    Full System Permissions (Administrator & Maestro)\n");
            xml.append("    Generated by GrantAllPermissions tool\n");
            xml.append("-->\n");
            xml.append("<permissions>\n");
            
            xml.append("    <!-- *************************************************************** -->\n");
            xml.append("    <!-- MAIN MENU & SYSTEM -->\n");
            xml.append("    <!-- *************************************************************** -->\n");
            xml.append("    <class name=\"Menu.Main\"/>\n");
            xml.append("    <class name=\"Menu.Sales\"/>\n");
            xml.append("    <class name=\"Menu.Customers\"/>\n");
            xml.append("    <class name=\"Menu.Stock\"/>\n");
            xml.append("    <class name=\"Menu.Inventory\"/>\n");
            xml.append("    <class name=\"Menu.Maintenance\"/>\n");
            xml.append("    <class name=\"Menu.System\"/>\n");
            xml.append("    <class name=\"Menu.ChangePassword\"/>\n");
            xml.append("    <class name=\"Menu.Exit\"/>\n");
            xml.append("    <class name=\"Menu.GlobalExpenses\"/>\n");

            xml.append("\n");
            xml.append("    <!-- *************************************************************** -->\n");
            xml.append("    <!-- SALES -->\n");
            xml.append("    <!-- *************************************************************** -->\n");
            xml.append("    <class name=\"com.openbravo.pos.sales.JPanelTicket\"/>\n");
            xml.append("    <class name=\"com.openbravo.pos.sales.JPanelTicketSales\"/>\n");
            xml.append("    <class name=\"com.openbravo.pos.sales.JPanelTicketEdits\"/>\n");
            xml.append("    <class name=\"sales.EditLines\"/>\n");
            xml.append("    <class name=\"sales.EditTicket\"/>\n");
            xml.append("    <class name=\"sales.RefundTicket\"/>\n");
            xml.append("    <class name=\"sales.PrintTicket\"/>\n");
            xml.append("    <class name=\"sales.Total\"/>\n");
            xml.append("    <class name=\"sales.Override\"/>\n");
            xml.append("    <class name=\"sales.ViewSharedTicket\"/>\n");
            xml.append("    <class name=\"sales.DeleteLines\"/>\n");
            xml.append("    <class name=\"sales.ChangeTaxOptions\"/>\n");
            xml.append("    <class name=\"sales.PrintKitchen\"/>\n");
            xml.append("    <class name=\"sales.TablePlan\"/>\n");
            xml.append("    <class name=\"sales.MoveTable\"/>\n");

            xml.append("\n");
            xml.append("    <!-- *************************************************************** -->\n");
            xml.append("    <!-- PAYMENTS -->\n");
            xml.append("    <!-- *************************************************************** -->\n");
            xml.append("    <class name=\"com.openbravo.pos.panels.JPanelPayments\"/>\n");
            xml.append("    <class name=\"com.openbravo.pos.panels.JPanelCloseMoney\"/>\n");
            xml.append("    <class name=\"com.openbravo.pos.panels.JPanelCloseMoneyReprint\"/>\n");
            xml.append("    <class name=\"payment.cash\"/>\n");
            xml.append("    <class name=\"payment.cheque\"/>\n");
            xml.append("    <class name=\"payment.paper\"/>\n");
            xml.append("    <class name=\"payment.magcard\"/>\n");
            xml.append("    <class name=\"payment.free\"/>\n");
            xml.append("    <class name=\"payment.debt\"/>\n");
            xml.append("    <class name=\"payment.gateway\"/>\n");
            xml.append("    <class name=\"payment.bank\"/>\n");
            xml.append("    <class name=\"payment.voucher\"/>\n");
            xml.append("    <class name=\"payment.slip\"/>\n");

            xml.append("\n");
            xml.append("    <!-- *************************************************************** -->\n");
            xml.append("    <!-- CUSTOMERS -->\n");
            xml.append("    <!-- *************************************************************** -->\n");
            xml.append("    <class name=\"com.openbravo.pos.forms.MenuCustomers\"/>\n");
            xml.append("    <class name=\"com.openbravo.pos.customers.CustomersPanel\"/>\n");
            xml.append("    <class name=\"com.openbravo.pos.customers.CustomersPayment\"/>\n");
            
            xml.append("\n");
            xml.append("    <!-- *************************************************************** -->\n");
            xml.append("    <!-- INVENTORY & STOCK -->\n");
            xml.append("    <!-- *************************************************************** -->\n");
            xml.append("    <class name=\"com.openbravo.pos.forms.MenuStockManagement\"/>\n");
            xml.append("    <class name=\"com.openbravo.pos.inventory.StockManagement\"/>\n");
            xml.append("    <class name=\"com.openbravo.pos.inventory.ProductsPanel\"/>\n");
            xml.append("    <class name=\"com.openbravo.pos.inventory.ProductsWarehousePanel\"/>\n");
            xml.append("    <class name=\"com.openbravo.pos.inventory.CategoriesPanel\"/>\n");
            xml.append("    <class name=\"com.openbravo.pos.inventory.TaxPanel\"/>\n");
            xml.append("    <class name=\"com.openbravo.pos.inventory.StockDiaryPanel\"/>\n");
            xml.append("    <class name=\"com.openbravo.pos.inventory.LocationsPanel\"/>\n");
            xml.append("    <class name=\"com.openbravo.pos.inventory.AttributeUsePanel\"/>\n");
            xml.append("    <class name=\"com.openbravo.pos.inventory.AttributeSetsPanel\"/>\n");
            xml.append("    <class name=\"com.openbravo.pos.inventory.AttributePanel\"/>\n");
            xml.append("    <class name=\"com.openbravo.pos.inventory.AttributeValuesPanel\"/>\n");
            xml.append("    <class name=\"com.openbravo.pos.inventory.AuxiliarPanel\"/>\n");
            xml.append("    <class name=\"com.openbravo.pos.inventory.BundlePanel\"/>\n");
            xml.append("    <class name=\"com.openbravo.pos.inventory.JPanelLowStock\"/>\n");
            xml.append("    <class name=\"com.openbravo.pos.inventory.JPanelAudit\"/>\n");
            xml.append("    <class name=\"com.openbravo.pos.inventory.TaxCategoriesPanel\"/>\n");
            xml.append("    <class name=\"com.openbravo.pos.inventory.TaxCustCategoriesPanel\"/>\n");
            xml.append("    <class name=\"com.openbravo.pos.inventory.UomPanel\"/>\n");
            
            xml.append("\n");
            xml.append("    <!-- *************************************************************** -->\n");
            xml.append("    <!-- MAINTENANCE & ADMIN -->\n");
            xml.append("    <!-- *************************************************************** -->\n");
            xml.append("    <class name=\"com.openbravo.pos.forms.MenuMaintenance\"/>\n");
            xml.append("    <class name=\"com.openbravo.pos.mant.JPanelPlaces\"/>\n");
            xml.append("    <class name=\"com.openbravo.pos.mant.JPanelFloors\"/>\n");
            xml.append("    <class name=\"com.openbravo.pos.admin.PeoplePanel\"/>\n");
            xml.append("    <class name=\"com.openbravo.pos.admin.RolesPanel\"/>\n");
            xml.append("    <class name=\"com.openbravo.pos.admin.ResourcesPanel\"/>\n");
            xml.append("    <class name=\"com.openbravo.pos.config.JPanelConfiguration\"/>\n");
            xml.append("    <class name=\"com.openbravo.pos.maintenance.JPanelDBMaintenance\"/>\n");
            xml.append("    <class name=\"com.openbravo.pos.printer.JPanelPrinter\"/>\n");
            xml.append("    <class name=\"com.openbravo.pos.panels.JPanelGlobalExpenses\"/>\n");
            
            xml.append("\n");
            xml.append("    <!-- *************************************************************** -->\n");
            xml.append("    <!-- SUPPLIERS -->\n");
            xml.append("    <!-- *************************************************************** -->\n");
            xml.append("    <class name=\"com.openbravo.pos.forms.MenuSuppliers\"/>\n");
            xml.append("    <class name=\"com.openbravo.pos.suppliers.SuppliersPanel\"/>\n");

            xml.append("\n");
            xml.append("    <!-- *************************************************************** -->\n");
            xml.append("    <!-- IMPORTS -->\n");
            xml.append("    <!-- *************************************************************** -->\n");
            xml.append("    <class name=\"com.openbravo.pos.imports.JPanelCSV\"/>\n");
            xml.append("    <class name=\"com.openbravo.pos.imports.JPanelCSVImport\"/>\n");
            xml.append("    <class name=\"com.openbravo.pos.imports.JPanelCSVCleardb\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/updatedprices.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/newproducts.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/missingdata.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/invaliddata.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/badprice.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/invalidcategory.bs\"/>\n");

            xml.append("\n");
            xml.append("    <!-- *************************************************************** -->\n");
            xml.append("    <!-- BUTTON SCRIPTS -->\n");
            xml.append("    <!-- *************************************************************** -->\n");
            xml.append("    <class name=\"button.totaldiscount\"/>\n");
            xml.append("    <class name=\"button.print\"/>\n");
            xml.append("    <class name=\"button.opendrawer\"/>\n");
            xml.append("    <class name=\"button.linediscount\"/>\n");
            xml.append("    <class name=\"button.sendorder\"/>\n");
            xml.append("    <class name=\"button.refundit\"/>\n");
            xml.append("    <class name=\"button.scharge\"/>\n");

            xml.append("\n");
            xml.append("    <!-- *************************************************************** -->\n");
            xml.append("    <!-- REPORTS -->\n");
            xml.append("    <!-- *************************************************************** -->\n");
            xml.append("    <class name=\"com.openbravo.pos.forms.MenuSalesManagement\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/sales_paymentsummary.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/closedpos.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/products.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/productscatalog.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/inventory.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/inventoryb.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/inventorybroken.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/inventorydiff.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/people.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/taxes.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/usersales.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/customers.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/customersb.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/closedproducts.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/chartsales.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/customers_sales.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/customers_debtors.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/customers_diary.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/customers_cards.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/customers_list.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/customers_export.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/suppliers.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/suppliers_b.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/suppliers_creditors.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/suppliers_diary.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/suppliers_list.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/suppliers_sales.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/suppliers_export.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/suppliers_products.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/barcode_sheet.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/barcode_shelfedgelabels.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/inventory_diary.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/inventorydiffdetail.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/inventorylistdetail.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/productlabels.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/salecatalog.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/sales_cashflow.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/sales_cashregisterlog.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/sales_categorysales.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/sales_closedpos.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/sales_closedpos_1.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/sales_closedproducts.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/sales_closedproducts_1.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/sales_extendedcashregisterlog.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/sales_extproducts.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/sales_paymentreport.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/sales_expenses.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/sales_productsalesprofit.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/sales_saletaxes.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/sales_taxcatsales.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/sales_taxes.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/sales_chart_chartsales.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/sales_chart_piesalescat.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/sales_chart_productsales.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/sales_chart_timeseriesproduct.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/sales_chart_top10sales.bs\"/>\n");
            xml.append("    <class name=\"/com/openbravo/reports/usernosales.bs\"/>\n");
            
            xml.append("</permissions>");
            
            System.out.println("Updating permissions...");
            new PreparedSentence(session, 
                "UPDATE ROLES SET PERMISSIONS = ? WHERE NAME IN ('Administrator', 'Administrador', 'maestro') OR ID = '0'",
                new SerializerWriteBasic(new Datas[]{Datas.BYTES}))
                .exec(new Object[]{xml.toString().getBytes()});

            System.out.println("Permissions updated for Administrator and Maestro.");
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
