CREATE TABLE IF NOT EXISTS merchandise_receipts (
    ID VARCHAR(255) PRIMARY KEY,
    DATENEW TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PERSON VARCHAR(255),
    STATUS VARCHAR(50) DEFAULT 'PENDING',
    NOTES TEXT
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS merchandise_receipt_lines (
    ID VARCHAR(255) PRIMARY KEY,
    RECEIPT_ID VARCHAR(255),
    PRODUCT_ID VARCHAR(255),
    UNITS DOUBLE,
    NOTES TEXT,
    FOREIGN KEY (RECEIPT_ID) REFERENCES merchandise_receipts(ID) ON DELETE CASCADE
) ENGINE=InnoDB;
